add controllers folder with controller for topics, add models folder with model for topics, add app.js and add test for GET /api/topics
DeanDevine/be-nc-news pull request #2
Opened 2023-06-26 15:06 UTC by DeanDevine

2023-06-26 15:20 UTC, roisinoreilly requested changes
a great start! I'd like you to add some tests for your errors and some error handling middleware, can you also add in a line to check that your array that you're iterating through isn't empty to avoid a false positive test. Once you've done that send us another PR :)

2023-06-26 15:20 UTC, roisinoreilly commented on __tests__/app.test.js
> +        topics.forEach((topic) => {
when we're iterating through an array such as this one, we need to check that it's not an empty array otherwise we'll get a false positive. Can you add in a line to this test to check the length please

2023-06-26 15:20 UTC, roisinoreilly commented on controllers/controller-topics.js
> +    console.log(err)
your controller shouldn't be handling your errors here, you should be passing the error to some middleware which will handle it. Have a look again at the notes if you're unsure https://notes.northcoders.com/courses/js-back-end/error-handling https://notes.northcoders.com/courses/js-back-end/middleware

2023-06-27 07:56 UTC, hevdevs commented on errors/index.js
> +    console.log(err);
remove console.log before merge

2023-06-27 07:56 UTC, hevdevs commented on app.js
> +app.all('*', (req, res) => {
Awesome!

2023-06-27 07:56 UTC, hevdevs approved these changes
Great stuff! Looks good to merge

2023-06-27 08:52 UTC, merged