add model/controller for /api/articles/:article_id/comments and relev…
DeanDevine/be-nc-news pull request #6
Opened 2023-06-28 07:32 UTC by DeanDevine

…ant tests, add error handling for 400, 404, update endpoints.json with path

2023-06-28 08:29 UTC, johnhutcheon commented on __tests__/app.test.js
> +            expect(comments).toHaveLength(11);
Nice work checking the length before using a forEach 👍

2023-06-28 08:30 UTC, johnhutcheon commented on __tests__/app.test.js
> +            expect(comments).toBeSorted('created_at', { ascending: true })
Thanks for implementing jest sorted as requested! 🙌

2023-06-28 08:30 UTC, johnhutcheon commented on __tests__/app.test.js
> +        })
Could we add one more test for a 200 please? What would we expect to happen if it’s a valid article ID but it has no comments?

2023-06-28 08:30 UTC, johnhutcheon commented on models/model-articles.js
> +            return Promise.reject({ status: 404, msg: "Not Found" })
Nicely done!

2023-06-28 08:31 UTC, johnhutcheon requested changes
Hi Dean, really good work! Could you just add the extra test as per my comments please? Thanks!

2023-06-28 09:47 UTC, MKD01 requested changes
Great work so far, you are almost there with this ticket but still missing a test, once you have added this back in please re-submit this as a new pr 👍

2023-06-28 09:47 UTC, MKD01 commented on __tests__/app.test.js
>          })
Here you have removed the test for when a valid id is given but does not exist, this was a really good test and should be in this ticket.

2023-06-28 12:58 UTC, daviidbartlett commented on __tests__/app.test.js
> +        return request(app)
this is off behaviour to design. I'm request all the comments associated with an article.
Assuming the article exists, I'm expect an array of all of the comments. If the there were no comments, that array would be empty. (Still a 200 though!)

2023-06-29 08:24 UTC, roisinoreilly approved these changes
nicely refactored :) PR approved merge when ready

2023-06-29 08:39 UTC, merged